# Generated by Django 2.2.4 on 2019-09-28 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('siglas', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('cp', models.CharField(blank=True, max_length=100, null=True)),
                ('web', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonos', models.CharField(blank=True, max_length=100, null=True)),
                ('emails', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Obra Social',
                'verbose_name_plural': 'Obras Sociales',
            },
        ),
        migrations.CreateModel(
            name='ObraSocialPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra_social_updated', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.CharField(max_length=90)),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='obras_sociales.ObraSocial')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2m_obras_sociales', to='pacientes.Paciente')),
            ],
        ),
    ]
