# Generated by Django 2.2.4 on 2019-10-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras_sociales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obrasocial',
            options={'permissions': [('can_view_tablero', 'Puede ver los tableros de comandos sobre obras sociales')], 'verbose_name': 'Obra Social', 'verbose_name_plural': 'Obras Sociales'},
        ),
    ]
