# Generated by Django 2.2.4 on 2019-11-12 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras_sociales', '0002_auto_20191028_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obrasocial',
            options={'permissions': [('can_view_tablero', 'Ver tableros de comandos')], 'verbose_name': 'Obra Social', 'verbose_name_plural': 'Obras Sociales'},
        ),
    ]
