# Generated by Django 2.2.4 on 2019-11-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras_sociales', '0003_auto_20191111_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocialpaciente',
            name='numero_afiliado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
