# Generated by Django 2.2.10 on 2020-04-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras_sociales', '0004_obrasocialpaciente_numero_afiliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocialpaciente',
            name='fecha_de_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obrasocialpaciente',
            name='fecha_de_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
