# Generated by Django 2.2.13 on 2020-08-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras_sociales', '0006_auto_20200721_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrasocialpaciente',
            name='parentesco',
            field=models.CharField(choices=[('conyuge', 'conyuge'), ('hijo', 'hijo'), ('otro', 'otro')], default='otro', max_length=20),
        ),
    ]
