# Generated by Django 2.2.13 on 2020-08-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras_sociales', '0007_correccion_conyuge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrasocialpaciente',
            name='tipo_beneficiario',
            field=models.CharField(choices=[('titular', 'titular'), ('no titular', 'no titular'), ('adherente', 'adherente')], default='titular', max_length=20),
        ),
    ]
