# Generated by Django 2.2.13 on 2020-09-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras_sociales', '0008_cambio_default_tipo_benef'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='obrasocialpaciente',
            constraint=models.UniqueConstraint(fields=('paciente', 'obra_social'), name='relacion_unica'),
        ),
    ]
