language: python
python:
  - 3.7
  - 3.8
services: 
  - postgresql
env:
  -DJANGO=2.2.8 DB=postgres
install:
  - pip install -r requirements.txt
  - pip install flake8
before_script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  - python manage.py test