# Generated by Django 2.2.4 on 2019-09-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carpetafamiliar',
            options={'verbose_name': 'Carpeta familiar', 'verbose_name_plural': 'Carpetas familiares'},
        ),
        migrations.AlterModelOptions(
            name='obrasocial',
            options={'verbose_name': 'Obra Social', 'verbose_name_plural': 'Obras Sociales'},
        ),
    ]
