# Generated by Django 2.2.4 on 2019-09-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190909_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='obra_social_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
