# Generated by Django 2.2.4 on 2019-09-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190909_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='carpeta_familiar',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='obra_social',
        ),
        migrations.DeleteModel(
            name='CarpetaFamiliar',
        ),
        migrations.DeleteModel(
            name='ObraSocial',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
