# Generated by Django 2.2.4 on 2019-09-24 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190921_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='obra_social',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='obra_social_updated',
        ),
        migrations.CreateModel(
            name='ObraSocialPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra_social_updated', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.CharField(max_length=90)),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='core.ObraSocial')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2m_obras_sociales', to='core.Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='obras_sociales',
            field=models.ManyToManyField(blank=True, through='core.ObraSocialPaciente', to='core.ObraSocial'),
        ),
    ]
