# Generated by Django 2.2.4 on 2019-09-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190924_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='cp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='domicilio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='emails',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='siglas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='telefonos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='web',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
