# Generated by Django 2.2.4 on 2019-09-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190927_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrasocial',
            name='nombre',
            field=models.CharField(max_length=240),
        ),
    ]
