# Generated by Django 2.2.4 on 2019-09-30 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('profesionales', '0005_auto_20190928_2338'),
        ('centros_de_salud', '0004_especialidad_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.Paciente')),
                ('profesional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesionales.Profesional')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centros_de_salud.Servicio')),
            ],
        ),
    ]
