# Generated by Django 2.2.4 on 2019-10-08 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Disponible'), (1, 'Asignado'), (2, 'Atendido'), (3, 'Cancelado por el paciente'), (4, 'Cancelado por el establecimiento')], default=0),
        ),
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.Paciente'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesionales.Profesional'),
        ),
    ]
