# Generated by Django 2.2.4 on 2019-11-16 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendario', '0003_auto_20191112_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Disponible'), (1, 'Asignado'), (2, 'Esperando en sala'), (3, 'Atendido'), (4, 'Cancelado por el paciente'), (5, 'Cancelado por el establecimiento')], default=0),
        ),
    ]
