# Generated by Django 2.2.4 on 2019-11-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0006_auto_20191116_1308'),
        ('calendario', '0004_auto_20191116_1323'),
    ]

    operations = [
    ]
