# Generated by Django 2.2.10 on 2020-05-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0008_auto_20191116_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'permissions': [('can_schedule_turno', 'Puede agendar un turno'), ('can_view_misturnos', 'Puede ver Mis Turnos'), ('can_cancel_turno', 'Puede cancelar sus turnos')]},
        ),
    ]
