# Generated by Django 2.2.13 on 2020-09-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obras_sociales', '0008_cambio_default_tipo_benef'),
        ('calendario', '0009_eliminacion_gestion_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='obras_sociales.ObraSocial'),
        ),
    ]
