# Generated by Django 2.2.4 on 2019-11-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centros_de_salud', '0010_auto_20191111_2348'),
        ('pacientes', '0008_consulta_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaAnexa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('observaciones_para_el_que_mide', models.TextField(blank=True, help_text='Texto que verá el profesional que mide', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedidasAnexasEspecialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatorio', models.BooleanField(default=True)),
                ('observaciones_para_el_que_mide', models.TextField(blank=True, help_text='Texto que verá el profesional que mide en esta especialidad', null=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas_anexas', to='centros_de_salud.Especialidad')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='especialidades.MedidaAnexa')),
            ],
        ),
        migrations.CreateModel(
            name='MedidaAnexaEnConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=8, default=0.0, max_digits=21)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas_anexas', to='pacientes.Consulta')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='especialidades.MedidaAnexa')),
            ],
        ),
    ]
