# Generated by Django 2.2.4 on 2019-11-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centros_de_salud', '0010_auto_20191111_2348'),
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medidasanexasespecialidad',
            unique_together={('especialidad', 'medida')},
        ),
    ]
