# Generated by Django 2.2.4 on 2019-09-09 21:57

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeSalud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=290)),
                ('horario_de_atencion', models.TextField(blank=True, null=True)),
                ('telefonos', models.TextField(blank=True, null=True)),
                ('direccion', address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Address')),
            ],
        ),
    ]
