# Generated by Django 2.2.4 on 2019-09-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centros_de_salud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrodesalud',
            options={'verbose_name': 'Centro de Salud', 'verbose_name_plural': 'Centros de Salud'},
        ),
    ]
