# Generated by Django 2.2.4 on 2019-09-26 00:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros_de_salud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodesalud',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centrodesalud',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
