# Generated by Django 2.2.4 on 2019-09-22 21:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centros_de_salud', '0002_auto_20190922_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodesalud',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Punto exacto de ubicación del lugar.', null=True, srid=4326),
        ),
    ]
