# Generated by Django 2.2.4 on 2019-09-30 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centros_de_salud', '0003_auto_20190926_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=290)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centros_de_salud.CentroDeSalud')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centros_de_salud.Especialidad')),
            ],
        ),
    ]
