# Generated by Django 2.2.4 on 2019-10-14 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centros_de_salud', '0004_especialidad_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=290)),
            ],
        ),
        migrations.AddField(
            model_name='centrodesalud',
            name='codigo_hpgd',
            field=models.CharField(blank=True, help_text='Código de Hospital Público de Gestión Descentralizada. Requerido para recupero', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='centrodesalud',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros', to='centros_de_salud.Institucion'),
        ),
    ]
