# Generated by Django 2.2.4 on 2019-10-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centros_de_salud', '0005_auto_20191014_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrodesalud',
            options={'permissions': [('can_view_tablero', 'Puede ver los tableros de comandos sobre centros de salud')], 'verbose_name': 'Centro de Salud', 'verbose_name_plural': 'Centros de Salud'},
        ),
    ]
