# Generated by Django 2.2.4 on 2019-10-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centros_de_salud', '0006_auto_20191028_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrodesalud',
            name='telefonos',
        ),
    ]
