# Generated by Django 2.2.4 on 2019-11-09 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0007_auto_20191109_1054'),
        ('centros_de_salud', '0007_auto_20191109_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesionalesEnServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveIntegerField(choices=[(100, 'Inactivo'), (200, 'Activo')], default=200)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='profesionales.Profesional')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='centros_de_salud.Servicio')),
            ],
        ),
    ]
