# Generated by Django 2.2.4 on 2019-11-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros_de_salud', '0008_profesionalesenservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='tiempo_predeterminado_turno',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
