# Generated by Django 2.2.4 on 2019-11-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0010_auto_20191117_1718'),
        ('centros_de_salud', '0010_auto_20191111_2348'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profesionalesenservicio',
            unique_together={('servicio', 'profesional')},
        ),
        migrations.AlterUniqueTogether(
            name='servicio',
            unique_together={('centro', 'especialidad')},
        ),
    ]
