# Generated by Django 2.2.4 on 2019-10-03 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cie10_django', '__first__'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='historia',
        ),
        migrations.AddField(
            model_name='consulta',
            name='codigo',
            field=models.ManyToManyField(blank=True, to='cie10_django.CIE10'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='historial_clinico', to='pacientes.Paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='derivaciones',
            field=models.ManyToManyField(blank=True, to='centros_de_salud.Especialidad'),
        ),
        migrations.DeleteModel(
            name='HistoriaClinica',
        ),
    ]
