# Generated by Django 2.2.4 on 2019-10-17 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0005_auto_20190928_2338'),
        ('pacientes', '0002_auto_20191003_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_clinico', to='profesionales.Profesional'),
        ),
    ]
