# Generated by Django 2.2.4 on 2019-11-04 02:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('centros_de_salud', '0006_auto_20191028_2329'),
        ('cie10_django', '0001_initial'),
        ('pacientes', '0003_consulta_profesional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='derivaciones',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='practicas',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='receta',
        ),
        migrations.AddField(
            model_name='consulta',
            name='codigo_cie_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnositicos_principales', to='cie10_django.CIE10'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='codigos_cie_secundarios',
            field=models.ManyToManyField(blank=True, related_name='diagnositicos_secundarios', to='cie10_django.CIE10'),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('medicamento', models.CharField(max_length=290)),
                ('posologia', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='pacientes.Consulta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones', to='pacientes.Consulta')),
                ('especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centros_de_salud.Especialidad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
