# Generated by Django 2.2.4 on 2019-11-04 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centros_de_salud', '0006_auto_20191028_2329'),
        ('pacientes', '0004_auto_20191103_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='centro_de_salud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='centros_de_salud.CentroDeSalud'),
        ),
    ]
