# Generated by Django 2.2.4 on 2019-09-23 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20190922_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefono',
            old_name='persona',
            new_name='paciente',
        ),
    ]
