# Generated by Django 2.2.4 on 2019-09-23 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0004_auto_20190922_2116'),
        ('pacientes', '0005_auto_20190923_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_clinico', to='pacientes.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('ultima_modificacion', models.DateField(auto_now_add=True)),
                ('diagnostico', models.TextField()),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('receta', models.TextField(blank=True, null=True)),
                ('practicas', models.TextField(blank=True, null=True)),
                ('derivaciones', models.ManyToManyField(blank=True, to='profesionales.Profesional')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.HistoriaClinica')),
            ],
        ),
    ]
