# Generated by Django 2.2.4 on 2019-11-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_auto_20191116_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='motivo_de_la_consulta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
