# Generated by Django 2.2.4 on 2019-11-18 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0008_auto_20191116_1616'),
        ('pacientes', '0012_auto_20191117_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='turno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendario.Turno'),
        ),
    ]
