# Generated by Django 2.2.13 on 2020-08-20 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0014_auto_20200426_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ultima_actualizacion',
            field=models.DateField(default=datetime.datetime(2020, 8, 20, 15, 5, 11, 19052)),
        ),
    ]
