# Generated by Django 2.2.4 on 2019-11-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioencentrodesalud',
            name='estado',
            field=models.PositiveIntegerField(choices=[(100, 'Inactivo'), (200, 'Activo')], default=200),
        ),
    ]
