# Generated by Django 2.2.10 on 2020-05-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20191110_2211'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuarioencentrodesalud',
            constraint=models.UniqueConstraint(fields=('usuario', 'centro_de_salud'), name='permiso_unico'),
        ),
    ]
