# Generated by Django 2.2.4 on 2019-10-22 00:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cie10_django', '0001_initial'),
        ('nhpgd_django', '0001_initial'),
        ('profesionales', '0006_profesional_dni'),
        ('centros_de_salud', '0005_auto_20191014_0001'),
        ('obras_sociales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAnexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_adjunto', models.FileField(upload_to='documentos_anexos')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('especialidad', models.CharField(max_length=50)),
                ('centro_de_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='centros_de_salud.CentroDeSalud')),
                ('cies_extras', models.ManyToManyField(blank=True, related_name='extras_facturas', to='cie10_django.CIE10')),
                ('codigo_cie_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='cie10_django.CIE10')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='obras_sociales.ObraSocial')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='profesionales.Profesional')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumentoAnexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Tipo de documento', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Tipo de atención', max_length=30)),
                ('tipo', models.PositiveIntegerField(choices=[(100, 'Consulta'), (200, 'Práctica'), (300, 'Internación')], default=100)),
                ('documentos_requeridos', models.ManyToManyField(blank=True, related_name='requerido_en_tipos', to='recupero.TipoDocumentoAnexo')),
                ('documentos_sugeridos', models.ManyToManyField(blank=True, related_name='sugerido_en_tipos', to='recupero.TipoDocumentoAnexo')),
            ],
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha de la prestación')),
                ('cantidad', models.IntegerField(default=1)),
                ('documentos_adjuntados', models.ManyToManyField(blank=True, to='recupero.DocumentoAnexo')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestaciones', to='recupero.Factura')),
                ('nomenclador', models.ForeignKey(help_text='Servicio realizado o entregado', on_delete=django.db.models.deletion.CASCADE, related_name='prestaciones', to='nhpgd_django.NomencladorHPGD')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recupero.TipoPrestacion')),
            ],
        ),
        migrations.AddField(
            model_name='documentoanexo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recupero.TipoDocumentoAnexo'),
        ),
    ]
