# Generated by Django 2.2.4 on 2019-11-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recupero', '0002_auto_20191103_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoprestacion',
            name='anio_update',
            field=models.PositiveIntegerField(default=2019, help_text='Si viene del nomenclador indicar de que versión es'),
        ),
    ]
