# Generated by Django 2.2.4 on 2019-11-04 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recupero', '0004_auto_20191103_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='centro_de_salud',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cies_extras',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='codigo_cie_principal',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='profesional',
        ),
        migrations.AddField(
            model_name='factura',
            name='prestacion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='recupero.Prestacion'),
            preserve_default=False,
        ),
    ]
