# Generated by Django 2.2.4 on 2019-11-08 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recupero', '0006_auto_20191105_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.PositiveIntegerField(choices=[(100, 'Nueva factura'), (200, 'Iniciado'), (300, 'Enviada'), (400, 'Rechazada'), (500, 'Aceptada'), (500, 'Pagada')], default=100),
        ),
        migrations.AlterField(
            model_name='factura',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='obras_sociales.ObraSocial'),
        ),
    ]
