# Generated by Django 2.2.4 on 2019-11-15 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_auto_20191109_1419'),
        ('recupero', '0007_auto_20191108_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='prestacion',
        ),
        migrations.AddField(
            model_name='factura',
            name='consulta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Consulta'),
        ),
    ]
