# Generated by Django 2.2.4 on 2019-11-15 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recupero', '0008_auto_20191114_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='consulta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='pacientes.Consulta'),
        ),
    ]
