# Generated by Django 2.2.10 on 2020-04-26 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recupero', '0009_auto_20191114_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
