# Generated by Django 2.2.10 on 2020-05-21 14:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recupero', '0010_factura_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoanexo',
            name='documento_adjunto',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/home/facu/stormTech/medicoCordoba/ggg/media', location='privado'), upload_to='documentos_anexos'),
        ),
    ]
