# Generated by Django 2.2.10 on 2020-05-24 19:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recupero', '0011_auto_20200521_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoanexo',
            name='documento_adjunto',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/hudson/dev/cluster311/ggg/file_private'), upload_to='documentos_anexos'),
        ),
    ]
