# Generated by Django 2.2.10 on 2020-06-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recupero', '0013_auto_20200613_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
