# Generated by Django 2.2.10 on 2020-06-16 13:27

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recupero', '0014_auto_20200613_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaprestacion',
            name='consulta',
        ),
        migrations.AddField(
            model_name='facturaprestacion',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prestacionesFactura', to='recupero.Factura'),
            preserve_default=False,
        ),
    ]
