# Generated by Django 2.2.10 on 2020-07-06 18:09

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centros_de_salud', '0011_auto_20191117_1800'),
        ('profesionales', '0010_auto_20191117_1718'),
        ('recupero', '0015_auto_20200616_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especialidad_factura', to='centros_de_salud.Especialidad'),
        ),
        migrations.AddField(
            model_name='factura',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesionales.Profesional'),
        ),
    ]
