# Generated by Django 2.2.13 on 2020-08-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recupero', '0016_auto_20200706_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.PositiveIntegerField(choices=[(100, 'Nueva factura'), (200, 'Iniciado'), (300, 'Enviada'), (400, 'Rechazada'), (500, 'Aceptada'), (600, 'Pagada')], default=100),
        ),
    ]
