# Generated by Django 2.2.13 on 2020-08-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recupero', '0017_auto_20200811_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_atencion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
