# Generated by Django 2.2.13 on 2020-09-09 19:03

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0018_auto_20200908_1102'),
        ('recupero', '0018_quitar_hora_fecha_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='empresa_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_paciente_factura', to='pacientes.EmpresaPaciente'),
        ),
    ]
