# Generated by Django 2.2.4 on 2019-09-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('matricula_profesional', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
