# Generated by Django 2.2.4 on 2019-09-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='domicilio',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='profesion',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='telefono',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='apellidos',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
