# Generated by Django 2.2.4 on 2019-09-22 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesional',
            options={'verbose_name_plural': 'Profesionales'},
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='dni',
        ),
        migrations.AddField(
            model_name='profesional',
            name='apellido',
            field=models.CharField(default='', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='profesional',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(2019, 9, 22)),
        ),
        migrations.AddField(
            model_name='profesional',
            name='nacionalidad',
            field=models.CharField(choices=[('argentina', 'argentina'), ('boliviana', 'boliviana'), ('brasilera', 'brasilera'), ('chilena', 'chilena'), ('colombiana', 'colombiana'), ('ecuatoriana', 'ecuatoriana'), ('paraguaya', 'paraguaya'), ('peruana', 'peruana'), ('uruguaya', 'uruguaya'), ('venezolana', 'venezolana'), ('otra', 'otra')], default='argentina', max_length=50),
        ),
        migrations.AddField(
            model_name='profesional',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Deje en blanco si está indocumentado', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino'), ('otro', 'otro')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profesional',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('LC', 'LC'), ('LE', 'LE'), ('PASAPORTE', 'PASAPORTE'), ('OTRO', 'OTRO')], default='DNI', max_length=20),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='nombres',
            field=models.CharField(max_length=50),
        ),
    ]
