# Generated by Django 2.2.4 on 2019-09-26 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0002_auto_20190924_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesional',
            options={'permissions': [('can_view_tablero', 'Puede ver los tableros de comandos sobre profesionales')]},
        ),
    ]
