# Generated by Django 2.2.4 on 2019-09-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0002_auto_20190922_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
    ]
