# Generated by Django 2.2.4 on 2019-09-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0003_auto_20190922_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino'), ('otro', 'otro')], max_length=20),
        ),
    ]
