# Generated by Django 2.2.4 on 2019-09-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0003_auto_20190926_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='departamento',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='localidad',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
    ]
