# Generated by Django 2.2.4 on 2019-09-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0004_auto_20190922_2116'),
        ('profesionales', '0002_auto_20190924_1931'),
    ]

    operations = [
    ]
