# Generated by Django 2.2.4 on 2019-09-28 23:38

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        ('profesionales', '0004_auto_20190927_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesional',
            options={'permissions': [('can_view_tablero', 'Puede ver los tableros de comandos sobre profesionales')], 'verbose_name_plural': 'Profesionales'},
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='telefono',
        ),
        migrations.AddField(
            model_name='profesional',
            name='direccion',
            field=address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Address'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='nacionalidad',
            field=models.CharField(choices=[('argentina', 'argentina'), ('boliviana', 'boliviana'), ('brasilera', 'brasilera'), ('chilena', 'chilena'), ('colombiana', 'colombiana'), ('ecuatoriana', 'ecuatoriana'), ('paraguaya', 'paraguaya'), ('peruana', 'peruana'), ('uruguaya', 'uruguaya'), ('venezolana', 'venezolana'), ('otra', 'otra')], default='argentina', max_length=50),
        ),
        migrations.AddField(
            model_name='profesional',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Deje en blanco si está indocumentado', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino'), ('otro', 'otro')], default='masculino', max_length=20),
        ),
        migrations.AddField(
            model_name='profesional',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('LC', 'LC'), ('LE', 'LE'), ('PASAPORTE', 'PASAPORTE'), ('OTRO', 'OTRO')], default='DNI', max_length=20),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='apellidos',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='nombres',
            field=models.CharField(max_length=50),
        ),
    ]
