# Generated by Django 2.2.4 on 2019-10-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0005_auto_20190928_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
