# Generated by Django 2.2.4 on 2019-11-09 13:54

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0006_profesional_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='dni',
        ),
        migrations.AlterField(
            model_name='profesional',
            name='direccion',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Address'),
        ),
    ]
