# Generated by Django 2.2.4 on 2019-10-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0006_profesional_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='dni',
        ),
    ]
